### PR TITLE
Fix build error for podman

### PR DESCRIPTION
**Pull request by JohannLange**
## Reason for the PR

The podman build failed for two reasons:

- for the UDM-Pro because the file `runc.Makefile.patch` didn't exist
- for the UDM-SE because `gperf` wasn't installed

## Changes

1. Create a single Dockerfile for both the UDM-Pro and UDM-SE.
The new Dockerfile will take in the arg `UDM_PLATFORM`, currently `UDM-Pro` and `UDM-SE` are supported.
Depending on the argument, the correct patch is copied.
1. Update the docker build command for the GitHub workflows.
1. Update the name of the UDM-Pro and UDM-SE in the workflows.
1. Fix some minor formatting errors in the markdowns.

### CODE REVIEW

**Comment by mazzy89** [comment]
Hi @JohannLange 

Thanks for the contribution. Did you test the build for both UDM Pro SE and UDM Pro locally?

**Comment by JohannLange** [comment]
> Hi @JohannLange
> 
> Thanks for the contribution. Did you test the build for both UDM Pro SE and UDM Pro locally?

Thank you :)

Yes, both `docker build --file podman-update/build/Dockerfile --build-arg UDM_PLATFORM=UDM-Pro --tag boostchicken:udmp-podman podman-update/build/` and `docker build --file podman-update/build/Dockerfile --build-arg UDM_PLATFORM=UDM-SE --tag boostchicken:udmp-podman podman-update/build/`
are being build successfully on my machine (x64)

**Comment by mazzy89** [comment]
cool thanks. could you please also make sure the artifacts produced are valid and they can run on the devices? As you see we do not have e2e tests so we need to make sure that not only the build runs fine but also that artifacts are ok and run fine.

**Comment by JohannLange** [comment]
> cool thanks. could you please also make sure the artifacts produced are valid and they can run on the devices? As you see we do not have e2e tests so we need to make sure that not only the build runs fine but also that artifacts are ok and run fine.

I don't have my UDM-SE yet, it's still in shipping.
But once it's set up, I'll try to run the artifact and report back!

**Comment by mazzy89** [comment]
Cool. Thanks a lot. Then looking forward. Once you are done please get back here and we'll push this out.

**Comment by leviathanprojects** [comment]
I'd be happy to test this on my SE. if that's helpful.

**Comment by leviathanprojects** [comment]
> > I'd be happy to test this on my SE. if that's helpful.
> 
> Sure! Works for me!
> 
> My SE is still in shipping 😡

Its a nice box, good to have poe built in!

So to test this on SE, do I need to install podman separately?  I cant see the zip artefact in the actions workflow that I assume contains podman?

**Comment by JohannLange** [comment]
> > > I'd be happy to test this on my SE. if that's helpful.
> > 
> > 
> > Sure! Works for me!
> > My SE is still in shipping 😡
> 
> Its a nice box, good to have poe built in!
> 
> So to test this on SE, do I need to install podman separately? I cant see the zip artefact in the actions workflow that I assume contains podman?

You cannot use the artifacts provided by GitHub.

You have to clone the repo and build the docker image via

```shell
docker build --file podman-update/build/Dockerfile --build-arg UDM_PLATFORM=UDM-SE --tag boostchicken:udmp-podman podman-update/build/
```

Then, you can extract the artifacts manually e.g. via:

```shell
docker run -it --rm --entrypoint /bin/bash boostchicken:udmp-podman
```

You'll see the hash of the container in the terminal as:

```shell
root@a1b2c3d4e5f6:/tmp/install
```

It is the part after the `@` and before the `:`.
Now run, in a new shell with the hash from above

```shell
docker cp a1b2c3d4e5f6:/tmp/release/podman-install.zip .
```

Now you copied the artifact to your local folder and from here, you can copy it to the UDM-SE

**Comment by boostchicken** [comment]
Looks like thge builds failed.  Go a head and fix it and ill merge

**Comment by JohannLange** [comment]
> Looks like thge builds failed. Go a head and fix it and ill merge

Turns out [QEMU was missing from the action](https://stackoverflow.com/questions/65161227/unable-to-build-docker-image-using-github-actions) to emulate the support for `arm64`.
I added the [latest version](https://github.com/marketplace/actions/docker-setup-qemu) of the [QEMU action](https://github.com/docker/setup-qemu-action) and now both builds, for the [UDM-Pro](https://github.com/JohannLange/udm-utilities/actions/runs/1975744594) and [UDM-SE](https://github.com/JohannLange/udm-utilities/actions/runs/1975744646), succeed.

**Comment by emilvissing** [comment]
this worked on my UDM-SE box. Thanks @JohannLange !

**Comment by JohannLange** [comment]
>

**Comment by JohannLange** [comment]
> this worked on my UDM-SE box. Thanks @JohannLange !

No problem, happy to help! :)

**Comment by gatesry** [comment]
I got some weird errors on the UDMP after taking your forked action’s artifacts and putting them in. I’ll upload logs in a sec.

**Comment by enavarrocu** [comment]
Also tested on my UDM-SE and works fine.

**Comment by JohannLange** [comment]
Can _finally_ confirm, works on my UDM-SE, too

**Comment by mazzy89** [comment]
Nice works. Going to approve then and feel free to merge it.

**Review by mazzy89 — APPROVED** [review]

**Pull request merged**
