### PR TITLE
[Feature] Remote install script

### PR DESCRIPTION
**Pull request by gtrabanco**
## Description

Install on boot scripts for udm, udr, udmpro, udmse and, (probably) next gen gateway (with a little modification).

## Motivation

Make easier and faster the installation of persistent boot scripts in any new UDM/R/Pro/SE machine.

## Tests

Only tested with UDM/SE. Probably a test with UDM-Pro or UDM before would be required before merge.

[EDIT]: Tested also on UDM and working. But I had to execute again the `/mnt/data/on_boot.d/05-install-cni-plugins.sh` script because gave me an error.

## Possible Unifi Next Gen Gateway support

I was not sure how it work if it work like UDM/Pro or UDMSE so I did not added compatibility.

To add it just modify the `udm_model` function to non give "unknow" and added the the possible value to the case in line `165` to the UDM or the UDMSE statement if it is the same as any of them.

### CODE REVIEW

**Comment by gtrabanco** [comment]
Edited PR message.

**Comment by boostchicken** [comment]
GFIve remote install a .sh file extension and modify the docmentatiojn on the main page to reflect this wonderful work

**Comment by gtrabanco** [comment]
Done

**Comment by gtrabanco** [comment]
Added CODEOWNER for the script as requested in #285

**Pull request merged**
